apiVersion: v1
kind: ConfigMap
metadata:
  name: config-br-default-channel
  namespace: cloud-run-events
data:
  channelTemplateSpec: |
    apiVersion: messaging.cloud.google.com/v1beta1
    kind: Channel
    spec:
      serviceAccountName: events-broker-gsa@PROJECT_ID.iam.gserviceaccount.com