apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: seldon-request-logger-trigger
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: seldon-request-logger

