apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: elastic-certificates
spec:
  backendType: gcpSecretsManager
  # Project to use for GCP Secrets Manager (use the service account project by default)
  projectId: ${PROJECT_ID}
  template: kubernetes.io/tls
  data:
      # Key in GCP Secrets Manager (without project and version)
    - key: elastic-cert
      name: elastic-certificates.p12
      version: latest
      binary: true
