apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: elastic-credentials
spec:
  backendType: gcpSecretsManager
  # Project to use for GCP Secrets Manager (use the service account project by default)
  projectId: ${PROJECT_ID}
  data:
    # Key in GCP Secrets Manager (without projet and version)
    - key: seldon-elastic-user
      name: user

    - key: seldon-elastic-secret
      name: pwd
