apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: kiali
spec:
  backendType: gcpSecretsManager
  # Project to use for GCP Secrets Manager (use the service account project by default)
  projectId: ${PROJECT_ID}
  data:
      # Key in GCP Secrets Manager (without project and version)
    - key: kiali-credentials
      name: username
      property: user
      version: latest
      isBinary: false

    - key: kiali-credentials
      name: passphrase
      property: password
      version: latest
      isBinary: false