apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: iris-model
  namespace: seldon
spec:
  name: iris-model
  predictors:
    - componentSpecs:
        - spec:
            containers:
              - name: classifier
                image: seldonio/sklearn-iris:0.1
      graph:
        children: []
        endpoint:
          type: REST
        name: classifier
        type: MODEL
      name: example
      replicas: 1